version: '3.8'

services:

  backend:
    container_name: rating_backend
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db
  
  frontend:
    container_name: rating_frontend
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  
  db:
    container_name: rating_db
    build:
      context: ./services/db
      dockerfile: Dockerfile
    volumes:
      - './services/db:/app'
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
